---
title: "Something about Me"
date: "2016-05-05T21:48:51-07:00"
---

#### Education Experience:
  * [2017.09 - 2019.05] **Georgetown University**, _Mathematics and Statistics_, **GPA**: 3.86/4.0
    * **Related course**: Numerical optimization, Probability Theory, Text mining, Intro to Neural Network, Cloud Computing
    
  * [2013.09 - 2017.07] **Xi'an Jiaotong Liverpool University**, _Financial Mathematics_, **First-class Honor**.
    * **Related course**: Hypothesis Testing, Econometrics, Operational Research, Stochastic Process, Statistical Distribution Theory
  
  - **Other fundamentals**: Calculus, Linear Algebra, Discrete Mathematics.

---

#### Skills:

* **Programming Language**: **Python (Tensorflow, sklearn)**, R, **C/C++**, SQL(MySQL, Postgresql), LaTeX, AWS (EC2, S3), Unix/Linux, git
* **Language**: Chinese (native speaker), English (fluent).

---

#### Projects

##### 1>- Hierarchical-BiLSTM Classifier of Sentiment on businesses on Yelp
    key words: Tensorflow, Attention, Hierarchical-BiLSTM, numpy, fasttext, DeepWalk.

* Parsed raw Json dataset and merged data on business ID; Processed texts, over-sampled dataset to resolve imbalanced classes distribution; Stored and shared data on AWS S3.

* Extracted TFIDF features for baselines (LR, NB, SVM from sklean) and fasttext embedding for Deep Learning model; Represented businesses tags/categories in a graph and trained graph-based representations by DeepWalk.
  
* Used Tensorflow to build bi-LSTM sentiment classifier in a hierarchical-based structure on texts along with pooled tag embeddings via self-attention. And increase the F1-score by 20\% over baselines.

---

##### 2>- CNN-LSTM Sentence Classification on Movie Reviews/Article Topics
    key words: Tensorflow, LSTM, TextCNN, GloVe

* Cleaned/Preprocessed text data and mapped words embeddings according to pre-trained GLoVe vectors. Built and trained model in Tensorflow.}
 
* Applied CNN to extract spatial-dependency features, on the top of which a stack of LSTMs were applied to fit temporal dependency among features.}

---

##### 3>- Network Embedding for Large Youtube Network Using DeepWalk 
    key words: Tensorflow, GNN, DeepWalk

* Cleaned and sampled the Youtube network nodes and construct power-law test.

* Built undirected network and extracted random walk sequences from each vertices.

* Encoded vertices into dense representations from sequences using Skip-gram model by analogy to language model.

## Others